use_frameworks!

platform :ios, '13.0'

target 'StreamingTextView_Example' do
  pod 'StreamingTextView', :path => '../'
  pod 'SDWebImage'
  pod 'Down'

  target 'StreamingTextView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase', '~> 2.1.4'
  end
end
